# Default Docker Compose (extends development)
include:
  - docker-compose.dev.yml

services:
  # Override for quick local development
  app:
    command: >
      sh -c "
        pnpm install &&
        pnpm run db:migrate &&
        pnpm run dev
      "
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres123@database:5432/cartrita_ai_agents
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}

volumes:
  postgres_data:
